output "main_cloudtrail_cloudtrailusernotification_cloudtrail_log_group_name" {
    value =  module.aws_cloudwatch_log_group.Cloudtrail_log_group.name
}

output "main_cloudwatch_cloudtrailusernotification_cloudtrail_cloudtrailusernotification_log_group_name" {
    value =  module.CLOUDTRAILLOGUSERNOTIFICATION.cloudwatch_cloudtrailusernotification_cloudtrailusernotification_cloudtrail_log_group_name
}