# Generated by Django 5.1.1 on 2024-10-17 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BarcodeT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_barcodes', models.IntegerField()),
                ('start_barcode', models.BigIntegerField()),
                ('last_barcode', models.BigIntegerField()),
                ('print_status', models.BooleanField(default=False)),
                ('dog', models.DateField(blank=True, null=True)),
                ('print_slot', models.CharField(default='Y', max_length=1, null=True)),
                ('gen_slot', models.CharField(default='Y', max_length=1, null=True)),
                ('Approval', models.CharField(default='R', max_length=1, null=True)),
            ],
            options={
                'db_table': 'BARCODE_T',
            },
        ),
    ]
