# Generated by Django 5.1.1 on 2024-10-23 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barcode', '0001_initial'),
        ('barcode_print', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barcodet',
            name='id',
        ),
        migrations.AddField(
            model_name='barcodet',
            name='b_type',
            field=models.ForeignKey(db_column='b_type', default=0, on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='barcode.typet'),
            preserve_default=False,
        ),
    ]
