# Generated by Django 5.1.1 on 2024-10-25 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barcode_print', '0002_remove_barcodet_id_barcodet_b_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barcodet',
            name='last_barcode',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='barcodet',
            name='start_barcode',
            field=models.BigIntegerField(default=0),
        ),
    ]
